### ISSUE TITLE
想扩展NodeTpl语法，让PHP与NodeTpl比较接近的保持一致模板语法

### ISSUE THREAD

**Issue by ljxok2001** [pillys/nodetpl#3]
像php的原生模板语法如下：
<? foreach ($array as $key => $value): ?>
    <? if(): ?>
    <? else if(): ?>
    <? endif ?>
<? endforeach ?>

<? for ($i = 0; $i <= 10; $i ++): ?>
<? endfor ?>

<? while(): ?>
<? endwhile ?>

**Comment by pillys** [comment]
已集成至 v4.5.0
